### ISSUE TITLE
Cannot find module 'react-dom/test-utils' from 'act-compat.js'

### ISSUE THREAD

**Issue by merraysy** [kentcdodds/react-testing-library#315]
- `react-testing-library` version: 6.0.0
- `react` version: 15.4.1
- `node` version: 8.11.3
- `npm` (or `yarn`) version: 1.12.3

### Relevant code or config:

```js
import 'react-testing-library/cleanup-after-each';
```

### What you did:

Just imported the `react-testing-library/cleanup-after-each`

### What happened:

Got this error `Cannot find module 'react-dom/test-utils' from 'act-compat.js'`

### Problem description:

The `react-addons-test-utils` was moved to `react-dom/test-utils` in the version `15.5`, that path doesn't work in `react-dom <15.5`

### Suggested solution:

Import from `react-addons-test-utils` or `react-dom/lib/ReactTestUtils` for `react-dom 15.4.x` versions, see this line
https://github.com/kentcdodds/react-testing-library/blob/master/src/act-compat.js#L3

**Comment by kentcdodds** [comment]
Hmmm... This is tricky because we generate a UMD build so we can't conditionally import based on your version of react. What do you think we could do?

**Comment by maksimgm** [comment]
Seeing this issue as well @merraysy

**Comment by jochakovsky** [comment]
I'm seeing this issue even though my project has a dependency on React 16.3 - apparently, one of the project's other dependencies has a dependency on React 15.2 and `jest-resolve` is getting confused? Anyone see anything similar?

**Comment by laila-vinson** [comment]
I have the same problem. 

```
react - 16.8.4

react-testing-library - 6.0.3

jest (installed via create-react-app) - 23.6.0
```

has anyone found a workaround for this?

**Comment by goosewobbler** [comment]
I see this bug with React 0.14.7 (upgrading not currently an option).  I worked around it by replacing the import on https://github.com/kentcdodds/react-testing-library/blob/master/src/act-compat.js#L3 with the code below.  It seems to build fine although the catch block is not covered by tests - if this approach is good enough for a PR maybe someone can find a way to test it, my efforts failed and `/* istanbul ignore next */` doesn't work for some reason.

```
let reactAct;

try {
  reactAct = require('react-dom/test-utils').default
} catch (e) { 
  reactAct = require('react-addons-test-utils').default
}
```

**Comment by merraysy** [comment]
@kentcdodds The issue reappeared again `v9.4.0` same react version.

> What do you think we could do?
Sorry I don't know how I've completely forgotten about this issue and never looked back :)

**Comment by kentcdodds** [comment]
Sorry about that. In thinking about this further, I'm afraid that the old approach we took will not work for all cases. So I'm going to suggest that you mock that module. I think if you put this in your `setupFilesAfterEnv` it should work without trouble:

```javascript
jest.mock('react-dom/test-utils', () => ({}))
```

Good luck!

**Comment by aralroca** [comment]
@kentcdodds I get the same issue after replace React to Preact.

**Comment by watofundefined** [comment]
For those who lands here after switching from React to Preact: [react-testing-library](https://github.com/testing-library/react-testing-library) -> [preact-testing-library](https://github.com/testing-library/preact-testing-library)

**Comment by gpspake** [comment]
Still having this same issue with updated versions:
```
  ● Test suite failed to run

    Cannot find module 'react-dom/test-utils' from 'node_modules/@testing-library/react/dist/act-compat.js'

    Require stack:
      node_modules/@testing-library/react/dist/act-compat.js
      node_modules/@testing-library/react/dist/index.js
      src/components/Icon/Icon.test.tsx

      at Resolver._throwModNotFoundError (node_modules/jest-resolve/build/resolver.js:491:11)
      at Object.<anonymous> (node_modules/@testing-library/react/dist/act-compat.js:10:41)
```

dependencies:
```
"@babel/core": "^7.18.2",
"@babel/preset-env": "^7.18.2",
"@babel/preset-react": "^7.17.12",
"@babel/preset-typescript": "^7.17.12",
"@rollup/plugin-commonjs": "^22.0.0",
"@rollup/plugin-node-resolve": "^13.3.0",
"@rollup/plugin-typescript": "^8.3.2",
"@testing-library/react": "^13.2.0",
"@types/jest": "^27.5.1",
"@types/react": "^18.0.9",
"babel-jest": "^28.1.0",
"classnames": "^2.3.1",
"jest": "^28.1.0",
"jest-environment-jsdom": "^28.1.0",
"postcss": "^8.4.14",
"react": "^18.1.0",
"rollup": "^2.74.1",
"rollup-plugin-dts": "^4.2.1",
"rollup-plugin-postcss": "^4.0.2",
"rollup-plugin-svg": "^2.0.0",
"rollup-plugin-svg-import": "^1.6.0",
"rollup-plugin-terser": "^7.0.2",
"ts-node": "^10.8.0",
"tslib": "^2.4.0",
"typescript": "^4.7.2",
"typescript-plugin-css-modules": "^3.4.0"
```
To reproduce: checkout https://github.com/gpspake/ui-next/tree/v1.0.4
and run `yarn && yarn test`
